import type { TemplateId } from "@/lib/league-city/templates";

export type Lang = "en" | "pt";
/** Who the town is for. Company towns start from a GitHub org check. */
export type Purpose = "community" | "friends" | "company";

type TemplateCopy = Record<TemplateId, { name: string; blurb: string }>;

export const COPY = {
  en: {
    back: "Towns",
    stepOf: (n: number, total: number) => `Step ${n} of ${total}`,
    labels: { purpose: "Who it's for", org: "Your org", name: "Name", template: "Starter city", create: "Create", share: "Call your people", build: "Build it" },
    purposeTitle: "Who is this town for?",
    purposeSub: "Every town gets its own 3D city, and every member becomes a building.",
    purposes: {
      community: { title: "My community", text: "A Discord, a meetup, a bootcamp. Members compete every week." },
      friends: { title: "Me and my friends", text: "Your crew in one town, built together." },
      company: { title: "My company", text: "Your GitHub org's town. Members verify on GitHub." },
    },
    nameTitle: { community: "Name your community's town", friends: "Name your town" },
    nameSub: "The name and logo go on the gate, the flags and the billboards.",
    nameLabel: { community: "Community name", friends: "Town name" },
    namePlaceholder: { community: "Tech In Rio", friends: "The Night Shift" },
    anyName: "Your town",
    logoLabel: "Logo",
    logoHint: "PNG or JPG, up to 1 MB. It turns into pixel art.",
    logoPick: "Upload logo",
    logoChange: "Change",
    logoBad: "Pick a PNG or JPG up to 1 MB.",
    templateTitle: "Pick a starter city",
    templateSub: "Streets, plazas and trees are ready from day one. You change anything later in the editor.",
    templates: {
      crew: { name: "Crew", blurb: "A main street and a plaza for your people." },
      park: { name: "Park village", blurb: "Few streets, lots of trees, a big plaza." },
      hq: { name: "Downtown", blurb: "City blocks, like a company HQ." },
      race: { name: "Race track", blurb: "A loop with ramps and boost pads." },
      blank: { name: "Blank", blurb: "Just the gate. Build everything yourself." },
    } satisfies TemplateCopy,
    createTitle: "Create the town",
    createSub: "Your building is the first one in town.",
    joinLabel: "Who can join",
    openTitle: "Anyone with the link",
    openText: "They click, sign in with GitHub and they're in.",
    recommended: { community: "Best for communities", friends: "Easiest" },
    askTitle: "Ask first",
    askText: "Each one asks to join and you approve them.",
    createCta: "Create the town",
    createSignIn: "Sign in with GitHub and create",
    creating: "Building your town…",
    claimFirst: "Claim your building in the city first, then come back to build a town.",
    claimCta: "Go to the city",
    networkError: "Network error. Try again.",
    createError: "Couldn't create the town.",
    logoError: "The town is ready, but the logo didn't upload. Add it later in the town's settings.",
    shareTitle: { community: "Call your community", friends: "Call your friends" },
    shareSub: { community: "Paste this in your Discord or Telegram. Every member who joins becomes a building.", friends: "Send this to your friends. Everyone who joins becomes a building." },
    linkLabel: "Your town's link",
    messageLabel: "Ready to paste",
    message: {
      community: (name: string, link: string) =>
        `We have a town in Git City now: ${name}. Join with GitHub and you become a building. Every Monday, whoever coded the most that week wins. ${link}`,
      friends: (name: string, link: string) => `I made us a town in Git City: ${name}. Join with GitHub and you become a building. ${link}`,
    },
    copy: "Copy",
    copyMessage: "Copy message",
    copied: "Copied",
    mondayTitle: "Every Monday",
    mondayText: "The week closes at 00:00 UTC. You get your place and your top coder, ready to post.",
    buildTitle: "Build it your way",
    buildSub: "The town is yours. Open the editor and place anything, on any lot.",
    tools: [
      { k: "Streets and plazas", v: "Draw roads lot by lot, open a plaza for your crowd." },
      { k: "Trees, fountains, benches", v: "Turn a block into a park." },
      { k: "Ramps and boost pads", v: "Everyone drives the town. Give them jumps." },
      { k: "Billboards and flags", v: "Your logo on every corner." },
    ],
    openEditor: "Open the editor",
    enter: "Enter your town",
    next: "Continue",
    backStep: "Back",
    member: "member",
    company: {
      orgTitle: "Find your org",
      orgSub: "One town per GitHub org. Your colleagues' buildings come in with it.",
      signInTitle: "Sign in with GitHub first",
      signInText: "We check your org on GitHub, so we need to know who you are.",
      signIn: "Sign in with GitHub",
      orgLabel: "Your org on GitHub",
      orgPlaceholder: "your-org",
      orgHint: "The name in its address: github.com/your-org.",
      yourOrgs: "Your orgs",
      checking: (org: string) => `Checking ${org ? `@${org}` : "the org"} on GitHub…`,
      badName: "That isn't a GitHub org name. Use the name in its address: github.com/name.",
      typeOrg: "Type your org's GitHub name.",
      checkError: "Couldn't check that org. Try again.",
      noAccount: (org: string) => `There's no @${org} on GitHub. Check the spelling in its address.`,
      person: (org: string) => `@${org} is a person's account, not an org.`,
      githubDown: "GitHub didn't answer. Try again in a moment.",
      notMember: (org: string) => `We can't see you in @${org}. Make your membership public, then check again.`,
      removed: (town: string) => `The admin of ${town} removed you. Ask them for a new invite.`,
      open: (town: string) => `You live in ${town}.`,
      inOrg: (org: string) => `You're in @${org}.`,
      builtAlready: (town: string, n: number) => `${town} is already built${n >= 2 ? `, ${n} buildings` : ""}.`,
      notBuilt: (town: string) => `${town} isn't built yet. You'll build it next.`,
      checkAgain: "Check again",
      tryAgain: "Try again",
      openTown: (town: string) => `Open ${town}`,
      buildTitle: (town: string) => `Build ${town}`,
      buildSub: "Members of your org join by checking the org on GitHub.",
      moveTitle: (town: string) => `Move into ${town}`,
      moveSub: "It's already built, so its city and settings come as they are.",
      moveInvited: "Your building is there with the lights off: move in to turn them on.",
      colleagues: (n: number | null) =>
        n === null ? "" : n > 0 ? `${n >= 100 ? "100+" : n} colleague${n === 1 ? "" : "s"} with a public membership come in as dark buildings and light up when they move in.` : "It's just you for now: colleagues move in when they check the org.",
      leaving: (town: string) => `You'll leave ${town}. You can live in one company town at a time.`,
      buildCta: (town: string) => `Build ${town}`,
      moveCta: (town: string) => `Move into ${town}`,
      moving: "Moving in…",
      buildings: "Buildings",
      whoJoins: "Who can join",
      membersOf: (org: string) => `Members of @${org}`,
      shareTitle: "Call your colleagues",
      shareSub: "Paste this in your team's Slack. Everyone in the org who joins becomes a building.",
      message: (town: string, org: string, link: string) =>
        `${town} has a town in Git City. Sign in with GitHub as a member of @${org} and you become a building. ${link}`,
      anyName: "Your company",
      guideOpen: "Make your membership public",
      guideToggle: "Private member? How to make it public",
      guide1: "Open your org's people page:",
      guide2a: "Find your name, click ",
      guide2b: " and pick ",
      guide3: "Come back and press Check again. GitHub can take a minute.",
      guideSafe: "We only check that you're a member. Never your code.",
      guidePrivate: (org: string) => `Rather keep it private? Try GitHub org access (works if @${org} allows Git City)`,
      verifyFailed: "GitHub sign-in failed. Try again.",
      changed: "The town changed since the check. Here's how it looks now.",
    },
  },
  pt: {
    back: "Towns",
    stepOf: (n: number, total: number) => `Passo ${n} de ${total}`,
    labels: { purpose: "Pra quem", org: "Sua org", name: "Nome", template: "Cidade inicial", create: "Criar", share: "Chame a galera", build: "Construa" },
    purposeTitle: "Pra quem é essa town?",
    purposeSub: "Toda town ganha uma cidade 3D só dela, e cada membro vira um prédio.",
    purposes: {
      community: { title: "Minha comunidade", text: "Um Discord, um meetup, um bootcamp. Os membros competem toda semana." },
      friends: { title: "Eu e meus amigos", text: "Sua galera numa town só, construída junto." },
      company: { title: "Minha empresa", text: "A town da sua org no GitHub. Os membros verificam no GitHub." },
    },
    nameTitle: { community: "Dê um nome à town da sua comunidade", friends: "Dê um nome à sua town" },
    nameSub: "O nome e o logo vão no portão, nas bandeiras e nos outdoors.",
    nameLabel: { community: "Nome da comunidade", friends: "Nome da town" },
    namePlaceholder: { community: "Tech In Rio", friends: "Turno da Noite" },
    anyName: "Sua town",
    logoLabel: "Logo",
    logoHint: "PNG ou JPG, até 1 MB. Ele vira pixel art.",
    logoPick: "Enviar logo",
    logoChange: "Trocar",
    logoBad: "Escolha um PNG ou JPG de até 1 MB.",
    templateTitle: "Escolha a cidade inicial",
    templateSub: "Ruas, praças e árvores prontas desde o primeiro dia. Depois você muda tudo no editor.",
    templates: {
      crew: { name: "Crew", blurb: "Uma rua principal e uma praça pra sua galera." },
      park: { name: "Vila do parque", blurb: "Poucas ruas, muitas árvores, uma praça grande." },
      hq: { name: "Centro", blurb: "Quarteirões de cidade, tipo sede de empresa." },
      race: { name: "Pista de corrida", blurb: "Um circuito com rampas e boost." },
      blank: { name: "Em branco", blurb: "Só o portão. Você constrói tudo." },
    } satisfies TemplateCopy,
    createTitle: "Crie a town",
    createSub: "Seu prédio é o primeiro da town.",
    joinLabel: "Quem pode entrar",
    openTitle: "Qualquer um com o link",
    openText: "Clica, entra com o GitHub e já está dentro.",
    recommended: { community: "Melhor pra comunidades", friends: "Mais fácil" },
    askTitle: "Com aprovação",
    askText: "Cada um pede pra entrar e você aprova.",
    createCta: "Criar a town",
    createSignIn: "Entrar com o GitHub e criar",
    creating: "Construindo sua town…",
    claimFirst: "Reivindique seu prédio na cidade primeiro, depois volte pra criar uma town.",
    claimCta: "Ir pra cidade",
    networkError: "Erro de rede. Tente de novo.",
    createError: "Não deu pra criar a town.",
    logoError: "A town está pronta, mas o logo não subiu. Adicione depois nas configurações da town.",
    shareTitle: { community: "Chame sua comunidade", friends: "Chame seus amigos" },
    shareSub: { community: "Cole isso no seu Discord ou Telegram. Cada membro que entra vira um prédio.", friends: "Mande isso pros seus amigos. Cada um que entra vira um prédio." },
    linkLabel: "O link da sua town",
    messageLabel: "Pronto pra colar",
    message: {
      community: (name: string, link: string) =>
        `Agora a gente tem uma town na Git City: ${name}. Entra com o GitHub e você vira um prédio. Toda segunda, quem mais programou na semana ganha. ${link}`,
      friends: (name: string, link: string) => `Criei uma town pra gente na Git City: ${name}. Entra com o GitHub e você vira um prédio. ${link}`,
    },
    copy: "Copiar",
    copyMessage: "Copiar mensagem",
    copied: "Copiado",
    mondayTitle: "Toda segunda",
    mondayText: "A semana fecha às 00:00 UTC. Você recebe sua posição e quem mais programou, pronto pra postar.",
    buildTitle: "Construa do seu jeito",
    buildSub: "A town é sua. Abra o editor e coloque o que quiser, em qualquer lote.",
    tools: [
      { k: "Ruas e praças", v: "Desenhe ruas lote por lote, abra uma praça pra galera." },
      { k: "Árvores, fontes, bancos", v: "Transforme um quarteirão num parque." },
      { k: "Rampas e boost", v: "Todo mundo dirige pela town. Dê saltos pra eles." },
      { k: "Outdoors e bandeiras", v: "Seu logo em cada esquina." },
    ],
    openEditor: "Abrir o editor",
    enter: "Entrar na town",
    next: "Continuar",
    backStep: "Voltar",
    member: "membro",
    company: {
      orgTitle: "Encontre sua org",
      orgSub: "Uma town por org no GitHub. Os prédios dos seus colegas vêm junto.",
      signInTitle: "Entre com o GitHub primeiro",
      signInText: "A gente confere sua org no GitHub, então precisa saber quem é você.",
      signIn: "Entrar com o GitHub",
      orgLabel: "Sua org no GitHub",
      orgPlaceholder: "sua-org",
      orgHint: "O nome no endereço dela: github.com/sua-org.",
      yourOrgs: "Suas orgs",
      checking: (org: string) => `Conferindo ${org ? `@${org}` : "a org"} no GitHub…`,
      badName: "Isso não é um nome de org do GitHub. Use o nome do endereço: github.com/nome.",
      typeOrg: "Digite o nome da sua org no GitHub.",
      checkError: "Não deu pra conferir essa org. Tente de novo.",
      noAccount: (org: string) => `Não existe @${org} no GitHub. Confira como está escrito no endereço.`,
      person: (org: string) => `@${org} é a conta de uma pessoa, não uma org.`,
      githubDown: "O GitHub não respondeu. Tente de novo daqui a pouco.",
      notMember: (org: string) => `A gente não te vê na @${org}. Deixe sua participação pública e confira de novo.`,
      removed: (town: string) => `O admin da ${town} te removeu. Peça um convite novo.`,
      open: (town: string) => `Você mora na ${town}.`,
      inOrg: (org: string) => `Você está na @${org}.`,
      builtAlready: (town: string, n: number) => `A ${town} já existe${n >= 2 ? `, ${n} prédios` : ""}.`,
      notBuilt: (town: string) => `A ${town} ainda não existe. Você constrói no próximo passo.`,
      checkAgain: "Conferir de novo",
      tryAgain: "Tentar de novo",
      openTown: (town: string) => `Abrir ${town}`,
      buildTitle: (town: string) => `Construa a ${town}`,
      buildSub: "Os membros da sua org entram conferindo a org no GitHub.",
      moveTitle: (town: string) => `Mude pra ${town}`,
      moveSub: "Ela já existe, então a cidade e as configurações vêm como estão.",
      moveInvited: "Seu prédio já está lá com as luzes apagadas: mude pra acender.",
      colleagues: (n: number | null) =>
        n === null ? "" : n > 0 ? `${n >= 100 ? "100+" : n} colega${n === 1 ? "" : "s"} com participação pública ${n === 1 ? "entra" : "entram"} como prédios apagados e ${n === 1 ? "acende" : "acendem"} quando ${n === 1 ? "se muda" : "se mudam"}.` : "Por enquanto é só você: os colegas se mudam quando conferem a org.",
      leaving: (town: string) => `Você vai sair da ${town}. Dá pra morar em uma town de empresa por vez.`,
      buildCta: (town: string) => `Construir a ${town}`,
      moveCta: (town: string) => `Mudar pra ${town}`,
      moving: "Mudando…",
      buildings: "Prédios",
      whoJoins: "Quem pode entrar",
      membersOf: (org: string) => `Membros da @${org}`,
      shareTitle: "Chame seus colegas",
      shareSub: "Cole isso no Slack do time. Cada pessoa da org que entra vira um prédio.",
      message: (town: string, org: string, link: string) =>
        `A ${town} tem uma town na Git City. Entra com o GitHub como membro da @${org} e você vira um prédio. ${link}`,
      anyName: "Sua empresa",
      guideOpen: "Deixe sua participação pública",
      guideToggle: "Membro privado? Como deixar público",
      guide1: "Abra a página de pessoas da sua org:",
      guide2a: "Ache seu nome, clique em ",
      guide2b: " e escolha ",
      guide3: "Volte e clique em Conferir de novo. O GitHub pode levar um minuto.",
      guideSafe: "A gente só confere se você é membro. Nunca o seu código.",
      guidePrivate: (org: string) => `Prefere manter privado? Tente o acesso de org do GitHub (funciona se a @${org} liberar a Git City)`,
      verifyFailed: "O login do GitHub falhou. Tente de novo.",
      changed: "A town mudou desde a conferência. Veja como ela está agora.",
    },
  },
};

export type WizardCopy = (typeof COPY)["en"];
