import type { TemplateId } from "@/lib/league-city/templates";

export type Lang = "en" | "pt";
/** Who the town is for. Company towns keep their own flow (GitHub org check). */
export type Purpose = "community" | "friends";

type TemplateCopy = Record<TemplateId, { name: string; blurb: string }>;

export const COPY = {
  en: {
    back: "Towns",
    stepOf: (n: number, total: number) => `Step ${n} of ${total}`,
    labels: { purpose: "Who it's for", name: "Name", template: "Starter city", create: "Create", share: "Call your people", build: "Build it" },
    purposeTitle: "Who is this town for?",
    purposeSub: "Every town gets its own 3D city, and every member becomes a building.",
    purposes: {
      community: { title: "My community", text: "A Discord, a meetup, a bootcamp. Members compete every week." },
      friends: { title: "Me and my friends", text: "Your crew in one town, built together." },
      company: { title: "My company", text: "Your GitHub org's town. Members verify on GitHub." },
    },
    nameTitle: { community: "Name your community's town", friends: "Name your town" },
    nameSub: "The name and logo go on the gate, the flags and the billboards.",
    nameLabel: { community: "Community name", friends: "Town name" },
    namePlaceholder: { community: "Tech In Rio", friends: "The Night Shift" },
    anyName: "Your town",
    logoLabel: "Logo",
    logoHint: "PNG or JPG, up to 1 MB. It turns into pixel art.",
    logoPick: "Upload logo",
    logoChange: "Change",
    logoBad: "Pick a PNG or JPG up to 1 MB.",
    templateTitle: "Pick a starter city",
    templateSub: "Streets, plazas and trees are ready from day one. You change anything later in the editor.",
    templates: {
      crew: { name: "Crew", blurb: "A main street and a plaza for your people." },
      park: { name: "Park village", blurb: "Few streets, lots of trees, a big plaza." },
      hq: { name: "Downtown", blurb: "City blocks, like a company HQ." },
      race: { name: "Race track", blurb: "A loop with ramps and boost pads." },
      blank: { name: "Blank", blurb: "Just the gate. Build everything yourself." },
    } satisfies TemplateCopy,
    createTitle: "Create the town",
    createSub: "Your building is the first one in town.",
    joinLabel: "Who can join",
    openTitle: "Anyone with the link",
    openText: "They click, sign in with GitHub and they're in.",
    recommended: { community: "Best for communities", friends: "Easiest" },
    askTitle: "Ask first",
    askText: "Each one asks to join and you approve them.",
    createCta: "Create the town",
    createSignIn: "Sign in with GitHub and create",
    creating: "Building your town…",
    claimFirst: "Claim your building in the city first, then come back to build a town.",
    claimCta: "Go to the city",
    networkError: "Network error. Try again.",
    createError: "Couldn't create the town.",
    logoError: "The town is ready, but the logo didn't upload. Add it later in the town's settings.",
    shareTitle: { community: "Call your community", friends: "Call your friends" },
    shareSub: { community: "Paste this in your Discord or Telegram. Every member who joins becomes a building.", friends: "Send this to your friends. Everyone who joins becomes a building." },
    linkLabel: "Your town's link",
    messageLabel: "Ready to paste",
    message: {
      community: (name: string, link: string) =>
        `We have a town in Git City now: ${name}. Join with GitHub and you become a building. Every Monday, whoever coded the most that week wins. ${link}`,
      friends: (name: string, link: string) => `I made us a town in Git City: ${name}. Join with GitHub and you become a building. ${link}`,
    },
    copy: "Copy",
    copyMessage: "Copy message",
    copied: "Copied",
    mondayTitle: "Every Monday",
    mondayText: "The week closes at 00:00 UTC. You get your place and your top coder, ready to post.",
    buildTitle: "Build it your way",
    buildSub: "The town is yours. Open the editor and place anything, on any lot.",
    tools: [
      { k: "Streets and plazas", v: "Draw roads lot by lot, open a plaza for your crowd." },
      { k: "Trees, fountains, benches", v: "Turn a block into a park." },
      { k: "Ramps and boost pads", v: "Everyone drives the town. Give them jumps." },
      { k: "Billboards and flags", v: "Your logo on every corner." },
    ],
    openEditor: "Open the editor",
    enter: "Enter your town",
    next: "Continue",
    backStep: "Back",
    member: "member",
  },
  pt: {
    back: "Towns",
    stepOf: (n: number, total: number) => `Passo ${n} de ${total}`,
    labels: { purpose: "Pra quem", name: "Nome", template: "Cidade inicial", create: "Criar", share: "Chame a galera", build: "Construa" },
    purposeTitle: "Pra quem é essa town?",
    purposeSub: "Toda town ganha uma cidade 3D só dela, e cada membro vira um prédio.",
    purposes: {
      community: { title: "Minha comunidade", text: "Um Discord, um meetup, um bootcamp. Os membros competem toda semana." },
      friends: { title: "Eu e meus amigos", text: "Sua galera numa town só, construída junto." },
      company: { title: "Minha empresa", text: "A town da sua org no GitHub. Os membros verificam no GitHub." },
    },
    nameTitle: { community: "Dê um nome à town da sua comunidade", friends: "Dê um nome à sua town" },
    nameSub: "O nome e o logo vão no portão, nas bandeiras e nos outdoors.",
    nameLabel: { community: "Nome da comunidade", friends: "Nome da town" },
    namePlaceholder: { community: "Tech In Rio", friends: "Turno da Noite" },
    anyName: "Sua town",
    logoLabel: "Logo",
    logoHint: "PNG ou JPG, até 1 MB. Ele vira pixel art.",
    logoPick: "Enviar logo",
    logoChange: "Trocar",
    logoBad: "Escolha um PNG ou JPG de até 1 MB.",
    templateTitle: "Escolha a cidade inicial",
    templateSub: "Ruas, praças e árvores prontas desde o primeiro dia. Depois você muda tudo no editor.",
    templates: {
      crew: { name: "Crew", blurb: "Uma rua principal e uma praça pra sua galera." },
      park: { name: "Vila do parque", blurb: "Poucas ruas, muitas árvores, uma praça grande." },
      hq: { name: "Centro", blurb: "Quarteirões de cidade, tipo sede de empresa." },
      race: { name: "Pista de corrida", blurb: "Um circuito com rampas e boost." },
      blank: { name: "Em branco", blurb: "Só o portão. Você constrói tudo." },
    } satisfies TemplateCopy,
    createTitle: "Crie a town",
    createSub: "Seu prédio é o primeiro da town.",
    joinLabel: "Quem pode entrar",
    openTitle: "Qualquer um com o link",
    openText: "Clica, entra com o GitHub e já está dentro.",
    recommended: { community: "Melhor pra comunidades", friends: "Mais fácil" },
    askTitle: "Com aprovação",
    askText: "Cada um pede pra entrar e você aprova.",
    createCta: "Criar a town",
    createSignIn: "Entrar com o GitHub e criar",
    creating: "Construindo sua town…",
    claimFirst: "Reivindique seu prédio na cidade primeiro, depois volte pra criar uma town.",
    claimCta: "Ir pra cidade",
    networkError: "Erro de rede. Tente de novo.",
    createError: "Não deu pra criar a town.",
    logoError: "A town está pronta, mas o logo não subiu. Adicione depois nas configurações da town.",
    shareTitle: { community: "Chame sua comunidade", friends: "Chame seus amigos" },
    shareSub: { community: "Cole isso no seu Discord ou Telegram. Cada membro que entra vira um prédio.", friends: "Mande isso pros seus amigos. Cada um que entra vira um prédio." },
    linkLabel: "O link da sua town",
    messageLabel: "Pronto pra colar",
    message: {
      community: (name: string, link: string) =>
        `Agora a gente tem uma town na Git City: ${name}. Entra com o GitHub e você vira um prédio. Toda segunda, quem mais programou na semana ganha. ${link}`,
      friends: (name: string, link: string) => `Criei uma town pra gente na Git City: ${name}. Entra com o GitHub e você vira um prédio. ${link}`,
    },
    copy: "Copiar",
    copyMessage: "Copiar mensagem",
    copied: "Copiado",
    mondayTitle: "Toda segunda",
    mondayText: "A semana fecha às 00:00 UTC. Você recebe sua posição e quem mais programou, pronto pra postar.",
    buildTitle: "Construa do seu jeito",
    buildSub: "A town é sua. Abra o editor e coloque o que quiser, em qualquer lote.",
    tools: [
      { k: "Ruas e praças", v: "Desenhe ruas lote por lote, abra uma praça pra galera." },
      { k: "Árvores, fontes, bancos", v: "Transforme um quarteirão num parque." },
      { k: "Rampas e boost", v: "Todo mundo dirige pela town. Dê saltos pra eles." },
      { k: "Outdoors e bandeiras", v: "Seu logo em cada esquina." },
    ],
    openEditor: "Abrir o editor",
    enter: "Entrar na town",
    next: "Continuar",
    backStep: "Voltar",
    member: "membro",
  },
};

export type WizardCopy = (typeof COPY)["en"];
